using Microsoft.VisualStudio.TestTools.UnitTesting;

//using RedBrick2;
//using SolidWorks.Interop.sldworks;

namespace RedBrickUnitTest {
	[TestClass]
	public class FmtFixtrBkTests {
		//[TestMethod]
		//public void scantest() {
		//	FormatFixtureBook.ExcelReader er_ = new FormatFixtureBook.ExcelReader(@"G:\ZALES\FIXTURE BOOK\SECTIONS\Section 4.xlsx",
		//		FormatFixtureBook.ExcelReader.ExcelReaderExtensionOptions.PDF,
		//		FormatFixtureBook.ExcelReader.ExcelReaderSearchOptions.RECURSE);
		//	var ll_ = er_.ReadFile();
		//	Assert.AreEqual(26, ll_.Count);
		//}


		//[TestMethod]
		//public void TestMethod1() {
		//	SldWorks app_ = null;
		//	try {
		//		app_ = System.Runtime.InteropServices.Marshal.GetActiveObject(@"SldWorks.Application") as SldWorks;
		//	} catch (System.Runtime.InteropServices.COMException e) {
		//		System.Console.WriteLine(e.Message);
		//	}
		//	//SwProperties p = new SwProperties(app_);
		//	//Assert.IsInstanceOfType(p, typeof(SwProperties));
		//	FormatFixtureBk ffb = new FormatFixtureBk(app_);
		//	ffb.Visible = true;
		//	ffb.Visible = false;
		//	ffb.ShowDialog();
		//}
	}
}
